"""
Configuration settings for the Product Shelf Analysis Tool
"""

import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Google Gemini API Configuration
# Try Streamlit secrets first, then fall back to environment variables
try:
    import streamlit as st
    GOOGLE_API_KEY = st.secrets["secrets"]["GOOGLE_API_KEY"]
except (ImportError, KeyError, FileNotFoundError):
    GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

# App Configuration
APP_TITLE = "Product Shelf Analysis Tool"
APP_DESCRIPTION = "Upload images of retail product displays and automatically detect SKU items using AI"

# UI Colors (Google Material Design)
COLORS = {
    "primary": "#4285F4",      # Google blue
    "secondary": "#34A853",    # Google green  
    "background": "#F8F9FA",   # Light grey
    "text": "#202124",         # Dark grey
    "accent": "#EA4335",       # Google red
    "success": "#137333"       # Dark green
}

# Default SKU items for detection
DEFAULT_SKU_ITEMS = [
    "AL BATAL CHEESE BALL 16/90G",
    "AL BATAL CHIPS BBQ FAMILY 16/110G",
    "AL BATAL CORN CURLS 16/90G",
    "AL BATAL POCORN W/CHO BIST PCS 16/140G",
    "AL BATAL POPCORN CARAMEL SEASALT 12/165G",
    "AL BATAL POPCORN CARML COATED 12/165G",
    "AL BATAL POPCORN COFEE & TOFEE 16/140G",
    "AL BATAL POPCORN JALPINNO CHESE 5/10/23G",
    "AL BATAL RIDGES CHILLI LEMON 12/155G",
    "AL BATAL RIDGES HOT SHATTA 12/155G",
    "AL-BATAL POPCORN BUTTER FLAV 4/11X23G",
    "AL-BATAL POPCORN HOT CHILLI 4/11X23G",
    "ALBATAL POPCORN BUTTER 12/100G",
    "ALBATAL POPCORN CHEESE 12/100G",
    "ALBATAL POPCRN HOT CHILI 12/100G",
    "ALBATAL POT CHIP SALT&VINEGR 12/120G",
    "ALBATAL POT CHIPS CHEESE 12/120G",
    "ALBATAL POT CHIPS KETCHUP 12/120G",
    "ALBATAL POT CHIPS SALT 12/120G",
    "ALBATAL REAL POT CHIP CHILLI 12/120G",
    "BKD IN BROK FLAT BRD ROSEMARY12/170GM",
    "BKD IN BROK FLAT BRD SRIRACHA 12/170GM",
    "BKD IN BROK PITA CHIPS S/SALT 12/170GM",
    "BKD IN BROK STICKS DILL PICKLE 12/170GM",
    "BKD IN BROK STICKS W/HON MUST 12/170GM",
    "BLANCO NINO CHILLI LIME TORTILLA 170G",
    "BLANCO NINO LIGHTLY SALTED CHIPS 170G",
    "BLANCO NINO SMKY CHPTLE TORTILLA 170G",
    "BUGLES BBQ 18/125G",
    "BUGLES BOX BBQ 6/12/15G",
    "BUGLES BOX ORIGINAL 6/12/15G",
    "BUGLES CORN SNACK BUFFALO WINGS  18/125G",
    "BUGLES CORN SNACK CHILLI & LIME   18/125G",
    "BUGLES CORN SNACK SWEET CHILI 20/35G",
    "BUGLES CORN SNACKS FIREY HOT 18/125G",
    "BUGLES KETCHUP 18/125G",
    "BUGLES NACHO CHEESE 8/7.5Z",
    "BUGLES ORIGINAL FLAVOUR  20/35G",
    "BUGLES SMOKIN BBQ FLAVOUR  20/35G",
    "BUGLES XXL BBQ 195GM",
    "CHEETOS CRUN FLAMIN HOT LIME 20/200G",
    "CHEETOS CRUNCH CHEESE 20/205G",
    "CHEETOS CRUNCH FH SCRMIN SIRCH 18/140G",
    "CHEETOS CRUNCHY FLAMIN HOT 20/200G",
    "CHEETOS CRUNCHY FLAMIN HOT 5/12/23G",
    "CHEETOS CRUNCHY FLAMIN' HOT 22/50G",
    "CHEETOS CRUNCHY FLAMING HOT 16/90G",
    "CHEETOS STICK CHSE/KETCHUP 4/14/30G",
    "CHEETOS STICKS CHEESE/KETCHUP 4/14/30G",
    "CHEETOS TWISTED CHEESE 18/160G",
    "CHEETOS TWISTED CHEESE 25/30G",
    "CHEX MIX MUDDY BUDDIES PNT BTTR 10/255G",
    "CRISPY LETTERS ABC KETCHUP 16X23Gm",
    "CRISPY RINGS CHEESE",
    "Crispy Rings Cheese 4x16x23g",
    "DEEMAH FARFASHA P.CHIP JALAPENO 20x75GM",
    "DEEMAH FARFASHA POT CHIP CHESE 8/12/21G",
    "DEEMAH FARFASHA POT CHIP CHILLI 8/12/21G",
    "DEEMAH FARFASHA STIX CHEESE 6/24/15G-1",
    "DEEMAH FARFASHA STIX CHILI&LMN 6/24/15G-1",
    "DEEMAH FARFASHA STIX JALAPENO 6/24/15G",
    "DEEMAH FARFASHA STIX KETCHUP 6/24/15G-1",
    "DEEMAH FARFASHA STIX SALT 6/24/15G-1",
    "DORITOS CRUNCH FH SCRMIN SIRCH 20/195G",
    "DORITOS DINAMITA FLAMIN HOT 20/145G",
    "DORITOS DINAMITA FLAMIN HOT 20/40G",
    "DORITOS FLAMIN HOT 20/175g",
    "DORITOS NACHO CHSE FMLY BAG 20/180G",
    "DORITOS NACHOO CHSE 1/20/48G",
    "DORITOS NACHOO CHSE 5/12/25G",
    "DORITOS SWT CHILLI PEPPER 1/20/48G",
    "DORITOS SWT CHILLI PEPPER 5/12/25G",
    "DORITOS SWT CHL PEPR FMLY BAG 20/180G",
    "DORITOS TORTLA CHIPS Nacho Chees 16/80G",
    "DORITOS TORTLA CHIPS SWT CHL PEPR 16/80G",
    "FANTAZEE CHEESE CURLS 12/130G",
    "FARFASHA CHILLI & LEMON CHIPS 20/75G",
    "FARFASHA CRUNCHY FLAMING HOT 5/20/20G",
    "FARFASHA CRUNCHY FLAMNG HOT 20/100G",
    "FARFASHA CRUNCHY NACHO CHEESE 20/100G",
    "FARFASHA FRENCH CHEESE CHIPS 20/75G",
    "FARFASHA JALAPENO PEPPER CHIPS 8/12/21G",
    "FARFASHA NATURAL SALT CHIPS 20/75G",
    "FARFASHA RANCH SAUCE CHIPS 20/75G",
    "FARFASHA RANCH SAUCE CHIPS 8/12/21G",
    "FARFASHA RANCH STICKS 10/24/15G",
    "FARFASHA SALT & VINEGAR CHIPS 20/75G",
    "FARFASHA TOMATO KETCHUP CHIPS 20/75G",
    "FL CHEDDAR JALAPENO CHEESE DIP 24/9OZ",
    "FL CHEETOS CRUNCHY FLAMIN HOT 24/3.5Z",
    "FL CHEETOS CRUNCHY FLAMIN LIMON 10/8Z",
    "FL CLASSIC REG POTATO CHIPS 12/6.5Z",
    "FL FUNYUNS ONION FLAVORED 44/21G",
    "FL KETTLE COOKED JALAPENO 18/6.5Z",
    "FL LAYS REGULAR POTATO CHIP 6/15Z",
    "FL LAYS SOUR CREAM & ONION 15/6.5Z",
    "FL LVL DORITOS SPICY SWT CHILLI 18/3.25",
    "FL MILD CHEDDAR CHEESE DIP 24/9Z",
    "FL ROLD GOLD C/S PRETZEL THIN 12/10Z",
    "FL RUFFLES SOUR CREAM & ONIONS 15/6.5Z",
    "FL SALT & VINEGAR POTATO CHIPS 12/6.5Z",
    "FL SANTITAS TORTILLA YLW CRN BREAD 6/10Z",
    "FL TOSTITOS CHNKY HABNERO SALSA 12/15.5Z",
    "FL TOSTITOS CHUNKY SALSA MILD 12/15.5OZ",
    "FL TOSTITOS CRISPY ROUNDS ORGNL 6/283.5G",
    "FL TOSTITOS HINT OF LIME 6/10OZ",
    "FRESHLY JALAPENO CHEESE SCE 12/14Z",
    "FRITO LAYS CHEETOS 44/1.25Z",
    "FRYMAS SNACKS ORIG 20/75G",
    "FRYMAS SNCKS BARBEQUE 20/75G",
    "FRYMAS SNCKS CHSE&ONION 20/75G",
    "FRYMAS SNCKS PAPRIKA 20/75G",
    "FRYMAS SNCKS SHASHLIK 20/75G",
    "GM CHEX MX MUDDY BUDDIES C/CRMB 10/9Z",
    "GOLDEN RING CHSE CRACKERS 6/10/60G",
    "GOLDEN RING ONION CRACKERS 6/10/60G",
    "HERRS CREAMY ONION DIP 24/241G",
    "HERRS CREAMY RANCH & HABANERO 12/6OZ",
    "HERRS CREAMY SPINACH DIP 12/15OZ",
    "HERRS JALAPENO CRUNCHY CHEESE STX 8/227G",
    "HERRS PEANUT BTTR PRETZELS BRRL 12/22OZ",
    "HERRS WHITE CORN TORTILLA CHIPS 9/9OZ",
    "HL FL RUFFLES POTATO CHIPS REG 15/6.5Z",
    "HL FL TOSTITOS RESTAURANT CHPS REG 6/10Z",
    "HL HERRS GHST PEPPR RPPLE CHIP 12/170G",
    "HL SIMPLY7 HUMUS SEA SALT CHIPS 12/142G*",
    "HL SIMPLY7 LENTIL CHIPS JALPNO 12/113G",
    "HL SIMPLY7 LNTIL CHIPS SEA SLT 12/113G*",
    "HL SIMPLY7 QUINOA CHIPS BARBEQUE 12/3.5Z",
    "HL TOSTITOS TRADITIONAL CANTINA 6/10OZ",
    "KITCO MEXITA TORTILA NACHO CHES 12/180GM",
    "KITCO MEXITA TORTILA S/CHLI PPER12/180GM",
    "KITCO MEXITA TORTILLA SWET&SOUR 12/180GM",
    "KITCO MEXITA TRTLA HOT CHLI&LIME 12/180G",
    "KITCO STIX GRILLED D CHICKEN 8/6/45G",
    "KITCO STIX HOT N SPICY 8/6/45G",
    "KITCO STIX LIGHTLY D SALTED 8/6/45G",
    "KITCO STIX TABASCO 8/6/45G",
    "KITCO STIX TOMATO D KETCHUP 8/6/45G",
    "LAYS CHEESE WITH PEPPER 20/165G",
    "LAYS CHILI LIME POTATO CHIPS 20/160G",
    "LAYS CRUNCH FH SCRMIN SIRCH 20/170G",
    "LAYS FRENCH CHEESE 20/50G",
    "LAYS FRENCH CHESSE POTATO CHIPS 12/21G",
    "LAYS HOT PAPRIKA 20/165G",
    "LAYS MANGO&HOT SPCS 165G",
    "LAYS MAXX CHICAGO HOTWINGS FLAV. 20/160G",
    "LAYS MAXX MEXICAN CHILI FLAV. 20/160G",
    "LAYS MAXX MEXICAN CHILI FLAV. 20/45G",
    "LAYS NAT POT CHIP CHILI 20/160G",
    "LAYS NAT POT CHIP FRENCH CHEESE 20/160G",
    "LAYS NAT POT CHIP KETCHUP 20/160G",
    "LAYS NAT POT CHIP SALT/VINEGAR 20/160G",
    "LAYS NAT POT CHIP SALTED 20/160G",
    "LAYS NAT POT CHIPS CHILI 4/14/25G",
    "LAYS POTATO CHIPS CHILLI 20/50G",
    "LAYS SALT POTATO CHIPS 20/50G",
    "LAYS SALT POTATO CHIPS 5/12/21G",
    "LAYS SALT&VINEGAR POTATO CHIPS 20/50G",
    "LAYS STAX BBQ 17/5.5Z",
    "LAYS STAX CHEDDAR 17/5.5 Z",
    "LAYS STAX ORIGINAL 11/5.75 OZ",
    "LAYS STAX SALT&VINEGAR 17/5.5Z",
    "LAYS STAX SOUR CREAM & ONION 17/155.9G",
    "LAYS TOMATO KETCHUP 20/50G",
    "LAYS TOMATO KETCHUP 5/12/21G",
    "LORENZ NATURAL MILD PAPRIKA 12/100G",
    "LORENZ NATURAL MIT ROSMARIN 12/100G",
    "LORENZ NATURAL SALT&PEPPER CHIPS 12/100G",
    "LORENZ POMSTICKS SALTED 20/100G-1",
    "Lays Stax BBQ 15/170g",
    "MIAOW MIAOW POTATO CHIPS 6/10X60G",
    "MIAOW MIAOW PRAWN HOT & SPICY 6/10X60G",
    "MR. KRISPS JALAPENO RINGS 12/65G",
    "MR. KRISPS TWIST SALTED POTATO 12/75G",
    "MR.KRISP CHSE BALL HOT SPCY CANST 12/80G",
    "MR.KRISP POT RINGS SALTD CANISTER 12/65G",
    "MR.KRISPS CHEESE BALLS CANISTER 12/80G",
    "OPEN NATURE VEGGIE CHIPS SEA SALT12/7Z",
    "OPEN NATURE VEGGIE STICKS SEA SALT 12/7Z",
    "PRINGLES BARBECUE  12/70G",
    "PRINGLES BBQ 19/165G",
    "PRINGLES BBQ 40G",
    "PRINGLES CHIPS HOT & SPICY XXL 19/200G",
    "PRINGLES CHIPS HOT CHEESY CHS XXL19/200G",
    "PRINGLES CHIPS HOT PAPRIKA XXL 19/200G",
    "PRINGLES CHIPS KETCHUP XXL 19/200G",
    "PRINGLES CHIPS ORIGINAL XXL 19/200G",
    "PRINGLES CHIPS SALT&VENIGAR XXL 19/200G",
    "PRINGLES CHIPS SIZZL SPICY BBQ 19/160G",
    "PRINGLES CHIPS SOUR CRM&ONIONXXL 19/200G",
    "PRINGLES CHIPS TEXAS BBQ SUCEXXL 19/200G",
    "PRINGLES DELI CHIPS CHEESE/ONION 19/200G",
    "PRINGLES DELI CHIPS PIZZA 19/200G",
    "PRINGLES HOT & SPICY 12/40G",
    "PRINGLES HOT & SPICY 12/70G",
    "PRINGLES HOT CHEESE CHILLI 19/160G",
    "PRINGLES HOT KICKIN SOUR CREAM 19/160G",
    "PRINGLES HOT MEXICAN CHILLI LIME 19/160G",
    "PRINGLES HOT SPICY BBQ 19/160G",
    "PRINGLES HOT SWEET CHILLI 19/160G",
    "PRINGLES HOT& SPICY 19/165G",
    "PRINGLES KETCHUP 12/70G",
    "PRINGLES KETCHUP 19/ 165G",
    "PRINGLES ORG 40G",
    "PRINGLES ORIGINAL 12/70G",
    "PRINGLES ORIGINAL 19/ 165G",
    "PRINGLES PAPRIKA 19/165G",
    "PRINGLES SALT& VINEGAR 19/165G",
    "PRINGLES SOUR CREAM  19/165G",
    "PRINGLES SWEET & SOUR ONION 12/70G",
    "S SEL PRETZEL O RINGS 6/28Z",
    "S SEL PRETZEL PEANUT BUTTER NUGGET 15/5Z",
    "S SEL VEGGIE STICKS BBQ 12/7Z",
    "S SEL VEGGIE STICKS RANCH 12/7Z",
    "SADAFCO CRISPY LETERS SALT&VINEGR 20/80G",
    "SADAFCO CRISPY LETTERS KETCHUP 20/90G",
    "SNACK POP OREO 12/149G",
    "STORCK WERTHERS POPCORN CARAMEL 14/140G",
    "SUN RING CHEESE 5/40/16G",
    "Samurai Cheese Rice Crackers 100gX24",
    "TAKIS WAVES BLUE HEAT CHIPS 226G",
    "TASALI CHILI & LEMON 14/90G",
    "TASALI CHILI CHIPS 90G",
    "TASALI CHILLI&LEMON 19/155g",
    "TASALI CHIPS CHILLI  19/165G",
    "TASALI CHIPS KETCHUP 19/165G",
    "TASALI CHIPS KETCHUP 20/90G",
    "TASALI CHIPS SPICY CREAM CHEESE 155G",
    "TASALI CUMIN LEMON 155g",
    "TASALI CUMIN LEMON 5/12/25G",
    "TAYLORS PKLED ONION 150G",
    "TAYLORS RGDE CT THAI SWEET CHIILI 150G",
    "TAYLORS SWEET & SALTED POPCORN 8/100G",
    "Takis Blue Heat Hot Chili Pepper Tortilla Chips 198gm",
    "WALKERS CRISPS READY SALTED 18/150G"
  ]

# File upload settings
MAX_FILE_SIZE_MB = 10
ALLOWED_EXTENSIONS = ['png', 'jpg', 'jpeg', 'webp']

# Gemini model settings  
GEMINI_MODEL = "gemini-2.5-pro"
DETECTION_PROMPT_TEMPLATE = """
Analyze this retail shelf/display image and identify products that match the following SKU items:

{sku_items}

For each detected item, provide:
1. Item name (from the SKU list)
2. Quantity/count visible
3. Shelf location (top, middle, bottom, left, right, etc.)
4. Confidence level (high/medium/low)

Return the results in JSON format with this structure:
{{
    "detected_items": [
        {{
            "item_name": "item name",
            "quantity": number,
            "location": "shelf location description", 
            "confidence": "high/medium/low",
            "notes": "any additional observations"
        }}
    ],
    "total_items_detected": number,
    "analysis_timestamp": "current timestamp"
}}

Be thorough but only include items you can clearly identify from the provided SKU list.
"""